set nocompatible
filetype off

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

Plugin 'gmarik/vundle'

" file manager
Plugin 'scrooloose/nerdtree'
nmap <F3> :NERDTreeToggle<CR>

" git plugin
Plugin 'tpope/vim-fugitive'

" code tags
Plugin 'majutsushi/tagbar'
nmap <F5> :TagbarToggle<CR>
Plugin 'taglist.vim'
" search for tags file in current dir, then traverse up til found
set tags=./tags;$HOME/workspace

" extra matches for % 
Plugin 'matchit.zip'

" autocomplete
"Plugin 'omniperl'
"Plugin 'perl-support.vim'
"Plugin 'ucompleteme'
"call ucompleteme#Setup()

"include pod.vim syntax file with perl.vim"
let perl_include_pod   = 1
"highlight complex expressions such as @{[$x, $y]}"
let perl_extended_vars = 1
"use more context for highlighting"
let perl_sync_dist     = 250

" tab manager
Plugin 'treelite/tabbar'


" markdown support
"Plugin 'Markdown'
"Plugin 'Markdown-syntax'
"Plugin 'godlygeek/tabular'
"Plugin 'plasticboy/vim-markdown'


" additional syntax, etc...


" unsorted
"Plugin 'ctrlp.vim'



" testing / temp / toggled





" Now we can turn our filetype functionality back on
filetype on
filetype plugin indent on

set shiftwidth=4
set tabstop=4
set noexpandtab
set smartindent

"colorscheme default
syntax enable
set number
set ruler

set hlsearch
set showmatch

set cursorline
set showcmd
set showmode
"set scrolloff=4


set foldmethod=manual
" show indicator column
set foldcolumn=3
" dont get too carried away
set foldnestmax=2
" dont fold initially
set foldlevel=99

" save and load folds
autocmd BufWinLeave *.* mkview
autocmd BufWinEnter *.* silent loadview

" toggle fold
nnoremap <silent> <F4> za
" set fold based on visual block
vnoremap <F4> zf
"let perl_fold = 1



" Easy window navigation
nmap <silent> <C-left> <C-w>h
nmap <silent> <C-down> <C-w>j
nmap <silent> <C-up> <C-w>k
nmap <silent> <C-right> <C-w>l
" then fix arrows in insert mode
imap <ESC>oA <ESC>ki
imap <ESC>oB <ESC>ji
imap <ESC>oC <ESC>li
imap <ESC>oD <ESC>hi



" hide fold and line numbers columns
nmap <F10> :set foldcolumn=0<CR>:set nonumber<CR>
imap <F10> <ESC>:set foldcolumn=0<CR>:set nonumber<CR>i

" show fold and line numbers columns
nmap <F9> :set foldcolumn=3<CR>:set number<CR>
imap <F9> <ESC>:set foldcolumn=3<CR>:set number<CR>i


" dont mess with formatting when pasting
set pastetoggle=<F2>



set nolazyredraw

" remove any trailing whitespace that is in the file
" Note: breaks markdown linebreaks (trailing double spaces)
"autocmd BufRead,BufWrite * if ! &bin | silent! %s/\s\+$//ge | endif

" no temp files
set nobackup
set nowritebackup
set noswapfile

